"""init

Revision ID: 4d0fa5dfb7f6
Revises: 
Create Date: 2026-05-04 13:17:15.556749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '4d0fa5dfb7f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('role', sa.Enum('creator', 'fan', 'admin', name='userrole'), nullable=False),
    sa.Column('provider', sa.Enum('email', 'kakao', 'google', name='authprovider'), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('profile_image_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_user_id'), 'credits', ['user_id'], unique=True)
    op.create_table('persona_weights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.Enum('pitch', 'rhythm', 'range', 'dynamic', 'articulation', name='personadimension'), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('bonus_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_weights_persona_id'), 'persona_weights', ['persona_id'], unique=False)
    op.create_table('ranking_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.Enum('weekly', 'monthly', name='periodtype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'archived', name='periodstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_periods_persona_id'), 'ranking_periods', ['persona_id'], unique=False)
    op.create_index(op.f('ix_ranking_periods_status'), 'ranking_periods', ['status'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('lyrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validating', 'scoring', 'scored', 'rejected', name='submissionstatus'), nullable=False),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ranking_mode', sa.Enum('ranking', 'challenge', 'both', name='rankingmode'), nullable=False),
    sa.Column('credit_used', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('base_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('pitch_score', sa.Float(), nullable=False),
    sa.Column('rhythm_score', sa.Float(), nullable=False),
    sa.Column('range_score', sa.Float(), nullable=False),
    sa.Column('dynamic_score', sa.Float(), nullable=False),
    sa.Column('articulation_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('processing_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_scores_submission_id'), 'base_scores', ['submission_id'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('purchase', 'submission', 'refund', 'bonus', 'admin', name='creditreason'), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('ranking_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('persona_score', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('is_survived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['ranking_periods.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_entries_period_id'), 'ranking_entries', ['period_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_submission_id'), 'ranking_entries', ['submission_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_user_id'), 'ranking_entries', ['user_id'], unique=False)
    op.create_table('submission_personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_personas_persona_id'), 'submission_personas', ['persona_id'], unique=False)
    op.create_index(op.f('ix_submission_personas_submission_id'), 'submission_personas', ['submission_id'], unique=False)
    op.create_table('tournament_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('unused', 'used', 'expired', name='ticketstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_tickets_persona_id'), 'tournament_tickets', ['persona_id'], unique=False)
    op.create_index(op.f('ix_tournament_tickets_status'), 'tournament_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tournament_tickets_submission_id'), 'tournament_tickets', ['submission_id'], unique=False)
    op.create_index(op.f('ix_tournament_tickets_user_id'), 'tournament_tickets', ['user_id'], unique=False)
    op.create_table('persona_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('base_score_id', sa.Uuid(), nullable=False),
    sa.Column('persona_score', sa.Float(), nullable=False),
    sa.Column('weighted_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_score_id'], ['base_scores.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_scores_persona_id'), 'persona_scores', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_scores_submission_id'), 'persona_scores', ['submission_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_score_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('improvements', sa.JSON(), nullable=True),
    sa.Column('next_challenge', sa.JSON(), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_score_id'], ['persona_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_persona_score_id'), 'feedbacks', ['persona_score_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_persona_score_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_persona_scores_submission_id'), table_name='persona_scores')
    op.drop_index(op.f('ix_persona_scores_persona_id'), table_name='persona_scores')
    op.drop_table('persona_scores')
    op.drop_index(op.f('ix_tournament_tickets_user_id'), table_name='tournament_tickets')
    op.drop_index(op.f('ix_tournament_tickets_submission_id'), table_name='tournament_tickets')
    op.drop_index(op.f('ix_tournament_tickets_status'), table_name='tournament_tickets')
    op.drop_index(op.f('ix_tournament_tickets_persona_id'), table_name='tournament_tickets')
    op.drop_table('tournament_tickets')
    op.drop_index(op.f('ix_submission_personas_submission_id'), table_name='submission_personas')
    op.drop_index(op.f('ix_submission_personas_persona_id'), table_name='submission_personas')
    op.drop_table('submission_personas')
    op.drop_index(op.f('ix_ranking_entries_user_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_submission_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_period_id'), table_name='ranking_entries')
    op.drop_table('ranking_entries')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_base_scores_submission_id'), table_name='base_scores')
    op.drop_table('base_scores')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_ranking_periods_status'), table_name='ranking_periods')
    op.drop_index(op.f('ix_ranking_periods_persona_id'), table_name='ranking_periods')
    op.drop_table('ranking_periods')
    op.drop_index(op.f('ix_persona_weights_persona_id'), table_name='persona_weights')
    op.drop_table('persona_weights')
    op.drop_index(op.f('ix_credits_user_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('personas')
    # ### end Alembic commands ###
